### ISSUE TITLE
ERROR: GF entries inconsistent with GFLibrary

### ISSUE THREAD

**Issue by eugenialocchi** [hvasbath/beat#101]
Hi
I'm trying to do example 4a with only seismic data (as I did for example 3). 
When I run the command "beat build_gfs Laquila --datatypes=seismic --mode=ffi --force --execute" I get this error : 

**Traceback (most recent call last):
  File "/usr/local/bin/beat", line 11, in <module>
    load_entry_point('beat==1.1.1', 'console_scripts', 'beat')()
  File "/usr/local/lib/python3.8/dist-packages/beat-1.1.1-py3.8-linux-x86_64.egg/beat/apps/beat.py", line 2122, in main
    globals()['command_' + command](args)
  File "/usr/local/lib/python3.8/dist-packages/beat-1.1.1-py3.8-linux-x86_64.egg/beat/apps/beat.py", line 1480, in command_build_gfs
    ffi.seis_construct_gf_linear(
  File "/usr/local/lib/python3.8/dist-packages/beat-1.1.1-py3.8-linux-x86_64.egg/beat/ffi/base.py", line 1175, in seis_construct_gf_linear
    for res in p:
  File "/usr/local/lib/python3.8/dist-packages/beat-1.1.1-py3.8-linux-x86_64.egg/beat/parallel.py", line 224, in paripool
    yield [function(*work)]
  File "/usr/local/lib/python3.8/dist-packages/beat-1.1.1-py3.8-linux-x86_64.egg/beat/ffi/base.py", line 1020, in _process_patch_seismic
    gfs.put(
  File "/usr/local/lib/python3.8/dist-packages/beat-1.1.1-py3.8-linux-x86_64.egg/beat/ffi/base.py", line 473, in put
    raise GFLibraryError(
beat.ffi.base.GFLibraryError: Trace length of entries is not consistent with the library to be filled! Entries length: 30 Library: 25.**

I've been using BEAT recently. Tell me if you need more information.
Thank you

Attached my configuration file.
[config_ffi.txt](https://github.com/hvasbath/beat/files/8609386/config_ffi.txt)

**Comment by hvasbath** [comment]
Hi!
Thank you for reporting that issue. Do you have already an existing GFLibrary in that project? If yes please remove it and rerun. If not I will need to try to debug using your config-file. But it may be a while until I get to it-as I have a lot to do currently.
Regards!
Hannes

**Comment by eugenialocchi** [comment]
Yes I have an existing GFLibrary in my project. Now the command works!!
 I changed the sample rate and  frequency to see if I could fix the problem!

Thank you very much!

**Comment by hvasbath** [comment]
Awesome! Please re-open if the issue pops up again!
