### ISSUE TITLE
Unable to download seismic data

### ISSUE THREAD

**Issue by WangJunyi2022** [hvasbath/beat#111]
Hello，Excuse me!
Recently,I can't use beatdown to download seismic data. When I try to download with the sample data, the following similar problems will occur. Is it because of the server network problem? (I have switched to another computer and wireless network, but still can't download).
---------------------------------------------------------------
wang@K:/media/wang/wjy/beat$:  beatdown /media/wang/wjy/beat "2009-04-06 01:32:39" 1000. 0.001 5. Laquila --nstations-wanted=60
Parsed arguments: ['/media/wang/wjy/menyuan6.4isce/beat', '2009-04-06 01:32:39', '1000.', '0.001', '5.', 'Laquila']
beatdown:root                 - INFO     - downloading channel information (geofon)
beatdown:root                 - INFO     - downloading channel information (iris)
beatdown:root                 - INFO     - downloading channel information (orfeus)
Traceback (most recent call last):
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/http/client.py", line 1291, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/http/client.py", line 1337, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/http/client.py", line 1286, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/http/client.py", line 956, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wang/anaconda3/envs/beat/bin/beatdown", line 33, in <module>
    sys.exit(load_entry_point('beat==1.1.1', 'console_scripts', 'beatdown')())
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/beat-1.1.1-py3.6-linux-x86_64.egg/beat/apps/beatdown.py", line 653, in main
    **extra_args)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/pyrocko/client/fdsn.py", line 441, in station
    check_params(service, site, url, majorversion, timeout, **kwargs)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/pyrocko/client/fdsn.py", line 808, in check_params
    service, site, url, majorversion, timeout, method)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/pyrocko/client/fdsn.py", line 856, in supported_params_wadl
    wadl = cached_wadl(service, site, url, majorversion, timeout)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/pyrocko/client/fdsn.py", line 932, in cached_wadl
    g_wadls[k] = wadl(service, site, url, majorversion, timeout)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/pyrocko/client/fdsn.py", line 905, in wadl
    wadl = load_xml(stream=_request(url, timeout=timeout))
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/pyrocko/client/fdsn.py", line 271, in _request
    resp = urlopen_(req, **url_args)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/site-packages/pyrocko/util.py", line 130, in urlopen
    return _urlopen(*args, **kwargs)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/wang/anaconda3/envs/beat/lib/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

**Comment by hvasbath** [comment]
Hi! Yes it seems to be a serverside issue. For now, I can just recommend you to try it again later....

**Comment by hvasbath** [comment]
Do you have an update on that? Did it work later?

**Comment by WangJunyi2022** [comment]
Hello, Professor. I later switched to a different Internet time period and connected to the mobile phone hotspot, but the download was not successful. I was wondering if I could use a virtual machine on my laptop for another network to download.
