### ISSUE TITLE
sample error with pymc version 5.17.0

### ISSUE THREAD

**Issue by CUMT530849827** [hvasbath/beat#134]
Dear developers, thank you very much for providing such excellent software. I found that I could not solve this error when I processed column 3, but I handled it normally on another computer without any error. My current beat version is 2.0.1, how should I deal with this error？
----------------------------------------------------------------------------------------------------------------------------------------------

(/opt/beat) root@ubuntu:~/Desktop# beat sample Laquila
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
To enable 'bem' mode packages 'pygmsh' and 'cutde' need to be installed.
config       - INFO     All hierarchicals ok!
config       - INFO     All hyperparameters ok!
config       - INFO     All priors ok!
models       - INFO     ... Initialising Geometry Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

models       - INFO     Using RectangularSource for 1 sources for event --- !pf.Event
lat: 42.29
lon: 13.35
time: '2009-04-06 01:32:49.190000057'
depth: 12000.0
name: '200904060132A'
magnitude: 6.343080192483292
region: 'CENTRAL ITALY'
catalog: 'gCMT'
moment_tensor: !pf.MomentTensor
  mnn: 1.43e+18
  mee: 1.87e+18
  mdd: -3.3e+18
  mne: 1.77e+18
  mnd: -1.43e+18
  med: 2.6900000000000003e+17
  strike1: 120.23408298515041
  dip1: 54.240869089580485
  rake1: -112.81739742081386
  strike2: 335.98575923255856
  dip2: 41.58440373860804
  rake2: -61.69749587601104
  moment: 3.6696131948749036e+18
  magnitude: 6.343080192483292
duration: 7.0

geodetic     - INFO     Number of geodetic datasets: 2 
geodetic     - INFO     Initialising corrections ...
heart        - INFO     Setting up Ramps correction for Laquila_dscxn
heart        - INFO     Masking data for Ramps estimation!
heart        - INFO     Not correcting Laquila_dscxn for Euler Pole
heart        - INFO     Not correcting Laquila_dscxn for Strain Rate
heart        - INFO     Setting up Ramps correction for Laquila_ascxn
heart        - INFO     Masking data for Ramps estimation!
heart        - INFO     Not correcting Laquila_ascxn for Euler Pole
heart        - INFO     Not correcting Laquila_ascxn for Strain Rate
geodetic     - INFO     Number of geodetic data points: 419 
geodetic     - INFO     Initialising geometry geodetic composite ...
models       - INFO     ... Building model ...

/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
models       - INFO     Initialised hyperparameter h_SAR with size 2 
models       - INFO     Initialized 2 hyperparameters in total!
geodetic     - INFO     Evaluating config for Ramps corrections for datasets...
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
geodetic     - INFO     Evaluating config for Euler Pole corrections for datasets...
geodetic     - INFO     No Euler Pole correction!
geodetic     - INFO     Evaluating config for Strain Rate corrections for datasets...
geodetic     - INFO     No Strain Rate correction!
geodetic     - INFO     Initialized 6 hierarchical parameters.
geodetic     - INFO     Geodetic optimization on: 
 depth, dip, east_shift, length, north_shift, rake, slip, strike, width
geodetic     - INFO     Retrieving geodetic data-covariances with structure "import" for Laquila_dscxn ...
geodetic     - INFO     Retrieving geodetic data-covariances with structure "import" for Laquila_ascxn ...
geodetic     - INFO     Applying corrections! ...
models       - INFO     Model building was successful! 

models       - INFO     Using "bin" backend to store samples!
models       - INFO     ... Initiate Sequential Monte Carlo ... 
 n_chains=1000, tune_interval=10, n_jobs=4, proposal_distribution: MultivariateCauchy, 

metropolis   - INFO     Creating initial population for 1000 chains ...
Sampling: [Laquila_ascxn_azimuth_ramp, Laquila_ascxn_offset, Laquila_ascxn_range_ramp, Laquila_dscxn_azimuth_ramp, Laquila_dscxn_offset, Laquila_dscxn_range_ramp, depth, dip, east_shift, h_SAR, length, north_shift, nucleation_x, nucleation_y, rake, slip, strike, time, width]
pymc.sampling.forward - INFO     Sampling: [Laquila_ascxn_azimuth_ramp, Laquila_ascxn_offset, Laquila_ascxn_range_ramp, Laquila_dscxn_azimuth_ramp, Laquila_dscxn_offset, Laquila_dscxn_range_ramp, depth, dip, east_shift, h_SAR, length, north_shift, nucleation_x, nucleation_y, rake, slip, strike, time, width]
metropolis   - INFO     Compiling model graph ...
Traceback (most recent call last):
  File "/opt/beat/bin/beat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/apps/beat.py", line 2442, in main
    globals()["command_" + command](args)
  File "/opt/beat/lib/python3.11/site-packages/beat/apps/beat.py", line 1064, in command_sample
    step = problem.init_sampler(hypers=options.hypers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/models/problems.py", line 175, in init_sampler
    step = sampler.SMC(
           ^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/sampler/smc.py", line 96, in __init__
    super(SMC, self).__init__(
  File "/opt/beat/lib/python3.11/site-packages/beat/sampler/metropolis.py", line 125, in __init__
    self.compile_model_graph(model)
  File "/opt/beat/lib/python3.11/site-packages/beat/sampler/metropolis.py", line 178, in compile_model_graph
    out_vars=[model.varlogp],
              ^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pymc/model/core.py", line 862, in varlogp
    return self.logp(vars=self.free_RVs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pymc/model/core.py", line 746, in logp
    rv_logps = transformed_conditional_logp(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pymc/logprob/basic.py", line 598, in transformed_conditional_logp
    temp_logp_terms = conditional_logp(
                      ^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pymc/logprob/basic.py", line 481, in conditional_logp
    fgraph = construct_ir_fgraph(rv_values, ir_rewriter=ir_rewriter)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pymc/logprob/rewriting.py", line 243, in construct_ir_fgraph
    replacements = tuple((rv, valued_rv(rv, value)) for rv, value in ir_rv_values.items())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pymc/logprob/rewriting.py", line 243, in <genexpr>
    replacements = tuple((rv, valued_rv(rv, value)) for rv, value in ir_rv_values.items())
                              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pytensor/graph/op.py", line 304, in __call__
    compute_test_value(node)
  File "/opt/beat/lib/python3.11/site-packages/pytensor/graph/op.py", line 125, in compute_test_value
    thunk()
  File "/opt/beat/lib/python3.11/site-packages/pytensor/graph/op.py", line 524, in rval
    r = p(n, [x[0] for x in i], o)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pymc/logprob/abstract.py", line 239, in perform
    raise NotImplementedError("ValuedVar should not be present in the final graph!")
NotImplementedError: ValuedVar should not be present in the final graph!
(/opt/beat) root@ubuntu:~/Desktop# 

-------------------------------------------------------------------------------------------------------------------------------------------

[BEAT_log.txt](https://github.com/user-attachments/files/17321491/BEAT_log.txt)

**Comment by hvasbath** [comment]
Hi! Please update to the latest version 2.0.3 that error was resolved with that update. Thank you!

**Comment by CUMT530849827** [comment]
Thanks for your reply, I updated beat to version 2.0.3 but it still reports the same error，I uploaded my data and yaml file and don't know where the error was

![image](https://github.com/user-attachments/assets/91b2b181-8cbf-42be-920d-955ee102cdda)
[Laquila.zip](https://github.com/user-attachments/files/17323721/Laquila.zip)

**Comment by hvasbath** [comment]
Whats your pymc version?

**Comment by CUMT530849827** [comment]
![image](https://github.com/user-attachments/assets/01ffa7e2-0115-4c40-914d-d041af2e8bc9)
5.17.0

**Comment by CUMT530849827** [comment]
It's starting to work properly Thank you very much for your guidance

**Comment by hvasbath** [comment]
Great thanks for reporting! Will need to pin the version of pymc then in the next release.

**Comment by CUMT530849827** [comment]
I used beat to complete the data processing of column 3 and got the same result as the case. However, I used my own data and the following error occurred. I only had insar data, so I made a new yaml file，How should I deal with this error
-----------------------------------------------------------------------------------------------------------------------------------

(/opt/beat) root@ubuntu:~/Desktop# beat sample mydz
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
To enable 'bem' mode packages 'pygmsh' and 'cutde' need to be installed.
config       - INFO     All hierarchicals ok!
config       - INFO     All hyperparameters ok!
config       - INFO     All priors ok!
models       - INFO     ... Initialising Geometry Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

models       - INFO     Using RectangularSource for 1 sources for event --- !pf.Event
lat: 37.81
lon: 101.31
time: '2022-01-07 17:45:32.089999914'
depth: 13700.0
name: '202201071745A'
magnitude: 6.686712302029662
region: 'QINGHAI, CHINA'
catalog: 'gCMT'
moment_tensor: !pf.MomentTensor
  mnn: 5.659999999999999e+18
  mee: -5.88e+18
  mdd: 2.1e+17
  mne: -1.04e+19
  mnd: 5.6e+17
  med: -1.67e+18
  strike1: 104.56241311967706
  dip1: 81.57891681425234
  rake1: 0.7926346174953631
  strike2: 14.446326877538597
  dip2: 89.21591169980759
  rake2: 171.57812248597253
  moment: 1.2024539492221729e+19
  magnitude: 6.686712302029662
duration: 10.4

geodetic     - INFO     Number of geodetic datasets: 1 
geodetic     - INFO     Initialising corrections ...
heart        - INFO     Setting up Ramps correction for myas_asc
heart        - INFO     Masking data for Ramps estimation!
heart        - INFO     Not correcting myas_asc for Euler Pole
heart        - INFO     Not correcting myas_asc for Strain Rate
geodetic     - INFO     Number of geodetic data points: 370 
geodetic     - INFO     Initialising geometry geodetic composite ...
models       - INFO     ... Building model ...

config       - INFO     not solving for opening_fraction, got fixed at 0.0
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
models       - INFO     Initialised hyperparameter h_SAR with size 1 
models       - INFO     Initialized 1 hyperparameters in total!
geodetic     - INFO     Evaluating config for Ramps corrections for datasets...
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
/opt/beat/lib/python3.11/site-packages/pymc/model/core.py:1453: UserWarning: To disable default transform, please use default_transform=None instead of transform=None. Setting transform to None will not have any effect in future.
  warnings.warn(
geodetic     - INFO     Evaluating config for Euler Pole corrections for datasets...
geodetic     - INFO     No Euler Pole correction!
geodetic     - INFO     Evaluating config for Strain Rate corrections for datasets...
geodetic     - INFO     No Strain Rate correction!
geodetic     - INFO     Initialized 3 hierarchical parameters.
geodetic     - INFO     Geodetic optimization on: 
 depth, dip, east_shift, length, north_shift, rake, slip, strike, width
Traceback (most recent call last):
  File "/opt/beat/bin/beat", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/apps/beat.py", line 2442, in main
    globals()["command_" + command](args)
  File "/opt/beat/lib/python3.11/site-packages/beat/apps/beat.py", line 1062, in command_sample
    problem = load_model(project_dir, options.mode, options.hypers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/models/problems.py", line 922, in load_model
    problem.built_model()
  File "/opt/beat/lib/python3.11/site-packages/beat/models/problems.py", line 241, in built_model
    total_llk += composite.get_formula(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/models/geodetic.py", line 635, in get_formula
    disp = self.get_synths(self.input_rvs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pytensor/graph/op.py", line 304, in __call__
    compute_test_value(node)
  File "/opt/beat/lib/python3.11/site-packages/pytensor/graph/op.py", line 125, in compute_test_value
    thunk()
  File "/opt/beat/lib/python3.11/site-packages/pytensor/graph/op.py", line 524, in rval
    r = p(n, [x[0] for x in i], o)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/pytensorf.py", line 118, in perform
    synths[0] = heart.geo_synthetics(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/beat/heart.py", line 4197, in geo_synthetics
    response = engine.process(sources, targets)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pyrocko/gf/seismosizer.py", line 5744, in process
    for ii_results, tcounters_static in process_static(
  File "/opt/beat/lib/python3.11/site-packages/pyrocko/gf/seismosizer.py", line 5247, in process_static
    base_statics, tcounters = engine.base_statics(
                              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pyrocko/gf/seismosizer.py", line 5585, in base_statics
    base_statics = store_.statics(
                   ^^^^^^^^^^^^^^^
  File "/opt/beat/lib/python3.11/site-packages/pyrocko/gf/store.py", line 2084, in statics
    res = store_ext.store_calc_static(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyrocko.gf.store_ext.StoreExtError: INDEX_OUT_OF_BOUNDS
-----------------------------------------------------------------------------------------------------------------------------
--- !beat.BEATconfig
name: mydz
date: '2022-01-07'
event: !pf.Event
  lat: 37.81
  lon: 101.31
  time: '2022-01-07 17:45:32.089999914'
  depth: 13700.0
  name: '202201071745A'
  magnitude: 6.686712302029662
  region: 'QINGHAI, CHINA'
  catalog: 'gCMT'
  moment_tensor: !pf.MomentTensor
    mnn: 5.659999999999999e+18
    mee: -5.88e+18
    mdd: 2.1e+17
    mne: -1.04e+19
    mnd: 5.6e+17
    med: -1.67e+18
    strike1: 104.56241311967706
    dip1: 81.57891681425234
    rake1: 0.7926346174953631
    strike2: 14.446326877538597
    dip2: 89.21591169980759
    rake2: 171.57812248597253
    moment: 1.2024539492221729e+19
    magnitude: 6.686712302029662
  duration: 10.4
project_dir: /root/Desktop/mydz
problem_config: !beat.ProblemConfig
  mode: geometry
  source_types:
  - RectangularSource
  stf_type: HalfSinusoid
  decimation_factors:
    geodetic: 4
  n_sources:
  - 1
  datatypes:
  - geodetic
  hyperparameters:
    h_SAR: !beat.heart.Parameter
      name: h_SAR
      form: Uniform
      lower:
      - -2.0
      upper:
      - 6.0
      testvalue:
      - 2.0
  priors:
    depth: !beat.heart.Parameter
      name: depth
      form: Uniform
      lower:
      - 0.0
      upper:
      - 5.0
      testvalue:
      - 1.0
    dip: !beat.heart.Parameter
      name: dip
      form: Uniform
      lower:
      - 45.0
      upper:
      - 90.0
      testvalue:
      - 63.0
    east_shift: !beat.heart.Parameter
      name: east_shift
      form: Uniform
      lower:
      - -10.0
      upper:
      - 10.0
      testvalue:
      - -8.0
    length: !beat.heart.Parameter
      name: length
      form: Uniform
      lower:
      - 5.0
      upper:
      - 30.0
      testvalue:
      - 11.0
    north_shift: !beat.heart.Parameter
      name: north_shift
      form: Uniform
      lower:
      - -10.0
      upper:
      - 10.0
      testvalue:
      - -8.0
    opening_fraction: !beat.heart.Parameter
      name: opening_fraction
      form: Uniform
      lower:
      - 0.0
      upper:
      - 0.0
      testvalue:
      - 0.0
    rake: !beat.heart.Parameter
      name: rake
      form: Uniform
      lower:
      - -90.0
      upper:
      - 90.0
      testvalue:
      - -72.0
    slip: !beat.heart.Parameter
      name: slip
      form: Uniform
      lower:
      - 0.1
      upper:
      - 8.0
      testvalue:
      - 1.7000000000000002
    strike: !beat.heart.Parameter
      name: strike
      form: Uniform
      lower:
      - 0.0
      upper:
      - 180.0
      testvalue:
      - 36.0
    width: !beat.heart.Parameter
      name: width
      form: Uniform
      lower:
      - 5.0
      upper:
      - 20.0
      testvalue:
      - 9.0
  hierarchicals:
    myas_asc_azimuth_ramp: !beat.heart.Parameter
      name: myas_asc_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    myas_asc_offset: !beat.heart.Parameter
      name: myas_asc_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.0
    myas_asc_range_ramp: !beat.heart.Parameter
      name: myas_asc_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
geodetic_config: !beat.GeodeticConfig
  types:
    SAR: !beat.SARDatasetConfig
      datadir: /root/Desktop/mydz/asc_data
      names:
      - myas_asc
  noise_estimator: !beat.GeodeticNoiseAnalyserConfig
    structure: import
    max_dist_perc: 0.2
  interpolation: multilinear
  corrections_config: !beat.GeodeticCorrectionsConfig
    euler_poles:
    - !beat.EulerPoleConfig
      enabled: false
    ramp: !beat.RampConfig
      dataset_names:
      - myas_asc
      enabled: true
    strain_rates:
    - !beat.StrainRateConfig
      enabled: false
  dataset_specific_residual_noise_estimation: false
  gf_config: !beat.GeodeticGFConfig
    reference_model_idx: 0
    n_variations:
    - 0
    - 1
    store_superdir: /root/Desktop/mydz/GF
    earth_model_name: ak135-f-continental.f
    nworkers: 1
    use_crust2: true
    replace_water: true
    source_depth_min: 0.0
    source_depth_max: 60.0
    source_depth_spacing: 1.0
    source_distance_radius: 20.0
    source_distance_spacing: 1.0
    error_depth: 0.1
    error_velocities: 0.1
    depth_limit_variation: 600.0
    version: ''
    code: psgrn
    sample_rate: 1.1574074074074073e-05
    sampling_interval: 1.0
    medium_depth_spacing: 1.0
    medium_distance_spacing: 10.0
sampler_config: !beat.SamplerConfig
  name: SMC
  backend: bin
  progressbar: true
  buffer_size: 5000
  buffer_thinning: 50
  parameters: !beat.SMCConfig
    tune_interval: 50
    check_bnd: true
    rm_flag: false
    n_jobs: 1
    n_steps: 100
    n_chains: 1000
    coef_variation: 1.0
    stage: 0
    proposal_dist: MultivariateNormal
    update_covariances: false
hyper_sampler_config: !beat.SamplerConfig
  name: Metropolis
  backend: bin
  progressbar: true
  buffer_size: 5000
  buffer_thinning: 50
  parameters: !beat.MetropolisConfig
    tune_interval: 50
    proposal_dist: Normal
    check_bnd: true
    rm_flag: false
    n_jobs: 1
    n_steps: 25000
    n_chains: 20
    thin: 2
    burn: 0.5

**Comment by CUMT530849827** [comment]
Thank you, Professor. I have completed List 3 and List 4 according to the instructions and the issue on github. beat is very attractive to me and I think it is a great software. I want to know more about it
