### ISSUE TITLE
Error：running "beat sample Laquila --hypers" in Scnario I

### ISSUE THREAD

**Issue by vic-chou** [hvasbath/beat#27]
Hi, I want to re-run the Scnario I, but when I run the "beat sample Laquila --hypers" in Scnario I, I meet an error
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Geometry Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 35 
geodetic     - INFO     Number of geodetic datasets: 2 
geodetic     - INFO     Number of geodetic data points: 419 
geodetic     - WARNING  Covariance estimation not implemented (yet)! Using imported covariances!
geodetic     - INFO     Fit residual ramp selected!
models       - INFO     ... Building Hyper model ...

geodetic     - INFO     Estimating ramp for each dataset...
geodetic     - INFO     Initialized 4 hierarchical parameters (ramps).
Traceback (most recent call last):
  File "beat/python35/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 1588, in main
    globals()['command_' + command](args)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 748, in command_sample
    project_dir, options.mode, options.hypers)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/models/problems.py", line 831, in load_model
    problem.built_hyper_model()
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/models/problems.py", line 260, in built_hyper_model
    self.init_hyperparams()
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/models/problems.py", line 400, in init_hyperparams
    raise NotImplementedError('Not fully implemented!')
NotImplementedError: Not fully implemented!

I did not change any values in configure file. Can you give me some suggestion?

**Comment by hvasbath** [comment]
Under seismic_config you enabled  " dataset_specific_residual_noise_estimation" please put that to false again!

**Comment by vic-chou** [comment]
I can run it successfully based on your suggestion. Thank you!
