### ISSUE TITLE
No such file or directory: geodetic_data.pkl in Scenario 0

### ISSUE THREAD

**Issue by nanfang0422** [hvasbath/beat#31]
Hi, Hannes

I met a problem when I was running scenario 0. When I type "beat check FullMT --what='traces'", it appears the error:
fangnandeMacBook-Pro:beat_learning NAN$ beat check FullMT --what='traces'
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Geometry Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/utility.py", line 871, in load_objects
    objects = pickle.load(open(loadpath, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/NAN/Documents/beat_learning/FullMT/geodetic_data.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1588, in main
    globals()['command_' + command](args)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1350, in command_check
    project_dir, options.mode, hypers=False, build=False)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 824, in load_model
    problem = problem_catalog[pc.mode](config, hypers)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 618, in __init__
    hypers)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/geodetic.py", line 432, in __init__
    gc, project_dir, sources, event, hypers=hypers)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/geodetic.py", line 335, in __init__
    gc, project_dir, event, hypers=hypers)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/geodetic.py", line 87, in __init__
    self.datasets = utility.load_objects(geodetic_data_path)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/utility.py", line 876, in load_objects
    'File %s does not exist!' % loadpath)
Exception: File /Users/NAN/Documents/beat_learning/FullMT/geodetic_data.pkl does not exist!

I don't know where the geodetic_data.pkl file is. Can you give me some suggestions? Thank you very much.

**Comment by hvasbath** [comment]
Hi Nan!

Thanks a lot for reporting! There is an issue in the Tutorial, I will update it. While cloning the sample directory please run:
beat clone FullMT /'model path'/FullMT --copy_data --datatypes=seismic

Instead of what is written in the tutorial now:
beat clone FullMT /'model path'/FullMT --copy_data

Best regards!
Hannes

**Comment by nanfang0422** [comment]
Thank you very much. I can run it successfully.
But I meet another problem in the next step.

fangnandeMacBook-Pro:beat_learning NAN$ beat sample FullMT --hypers
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Geometry Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 20 
seismic      - INFO     The waveform defined in "slowest 1" config is not included in the optimization!
models       - INFO     ... Building Hyper model ...

Traceback (most recent call last):
  File "/anaconda3/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1588, in main
    globals()['command_' + command](args)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 748, in command_sample
    project_dir, options.mode, options.hypers)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 831, in load_model
    problem.built_hyper_model()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 260, in built_hyper_model
    self.init_hyperparams()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 411, in init_hyperparams
    ' hyperparameter(s): %s!' % hp_name)
beat.models.problems.InconsistentNumberHyperparametersError: 
Datasets and -types require additional  hyperparameter(s): h_any_P_0_T!
Configuration file has to be updated! Hyperparameters have to be re-estimated. 
 Please run "beat update <project_dir> --parameters=hypers, hierarchicals"

In my config_geometry.yaml, the hyperparameters are:
hyperparameters:
    h_any_P_0_Z: !beat.heart.Parameter
      name: h_any_P_0_Z
      form: Uniform
      lower: [0.0]
      upper: [5.0]
      testvalue: [2.0]
    h_any_P_1_T: !beat.heart.Parameter
      name: h_any_P_1_T
      form: Uniform
      lower: [0.0]
      upper: [6.0]
      testvalue: [3.0]

I try to update the conifguration:
fangnandeMacBook-Pro:beat_learning NAN$ beat update FullMT --parameters='hypers, hierarchicals'
config       - INFO     Added hyperparameter h_any_P_0_Z to config and model setup!
config       - INFO     Added hyperparameter h_any_P_0_T to config and model setup!
config       - INFO     All hyper-parameters ok!
config       - INFO     Number of hyperparameters! 2
config       - INFO     All hierarchical-parameters ok!
config       - INFO     Number of hierarchicals! 0
upgrade      - INFO     Updated hyper parameters! Previous hyper parameter bounds are invalid now!
upgrade      - INFO     Updated hierarchicals.

Then, I run the code again:
fangnandeMacBook-Pro:beat_learning NAN$ beat sample FullMT --hypers
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Geometry Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 20 
seismic      - INFO     The waveform defined in "slowest 1" config is not included in the optimization!
models       - INFO     ... Building Hyper model ...

Traceback (most recent call last):
  File "/anaconda3/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1588, in main
    globals()['command_' + command](args)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 748, in command_sample
    project_dir, options.mode, options.hypers)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 831, in load_model
    problem.built_hyper_model()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 260, in built_hyper_model
    self.init_hyperparams()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/models/problems.py", line 411, in init_hyperparams
    ' hyperparameter(s): %s!' % hp_name)
beat.models.problems.InconsistentNumberHyperparametersError: 
Datasets and -types require additional  hyperparameter(s): h_any_P_0_T!
Configuration file has to be updated! Hyperparameters have to be re-estimated. 
 Please run "beat update <project_dir> --parameters=hypers, hierarchicals"
sam
It appears the same error. This is my hyper_sampler_config:
hyper_sampler_config: !beat.SamplerConfig
  name: Metropolis
  progressbar: true
  buffer_size: 5000
  parameters: !beat.MetropolisConfig
    tune_interval: 50
    proposal_dist: Normal
    check_bnd: true
    rm_flag: false
    n_jobs: 4
    n_steps: 25000
    n_chains: 20
    thin: 5
    burn: 0.5

Can you give me some suggestions? Thank you very much.

**Comment by hvasbath** [comment]
Next time please open a new issue!
Unfortunately I cannot reproduce your issue. Please run again:
beat update FullMT --parameters=hypers,hierarchicals

Without editing anything in the file please try sampling the hyperparameters now.
beat sample FullMT --hypers

If this does not work I will need to see your full config file. Best would be if you send it via email. Thanks for reporting!

**Comment by nanfang0422** [comment]
Sorry, I will remember to open a new issue when I meet new problems.
Thank you for your suggestions! 
I  have run the code you suggested again and it did work. Now I can run the whole scenario 0. 
I don't know where that problem comes and I will check it again. 
The attachment is my BEAT_log.txt.
[BEAT_log.txt](https://github.com/hvasbath/beat/files/2810539/BEAT_log.txt)
