### ISSUE TITLE
TypeError: Datatype "seismic" not included in FaultGeometry

### ISSUE THREAD

**Issue by nanfang0422** [hvasbath/beat#36]
Hi Hannes,
when I run the code "beat build_gfs Laquila_kinematic --datatypes=seismic --execute --mode=ffo
" in Scenario III, it appears the error:
fangnandeMacBook-Pro:beat_learning NAN$ beat build_gfs Laquila_kinematic --datatypes=seismic --execute --mode=ffo
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
beat         - INFO     Discretized fault geometry exists! Use --force to overwrite!
beat         - INFO     Loading existing discretized fault
beat         - INFO     Calculating linear Green's Functions
beat         - INFO     for seismic data ...
beat         - INFO     crust_ind 0
heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 35 
ffo          - INFO     Calculating GFs for starttimes: "-13.0", "-12.0", "-11.0", "-10.0", "-9.0", "-8.0", "-7.0", "-6.0", "-5.0", "-4.0", "-3.0", "-2.0", "-1.0", "0.0", "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "11.0", "12.0", "13.0", "14.0", "15.0" 
 durations: "0.0", "0.25", "0.5", "0.75", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "3.25", "3.5", "3.75", "4.0"
ffo          - INFO     Using 4 workers ...
ffo          - INFO     For slip component: uparr
Traceback (most recent call last):
  File "/anaconda3/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1588, in main
    globals()['command_' + command](args)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/apps/beat.py", line 1144, in command_build_gfs
    force=options.force)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/ffo/base.py", line 1043, in seis_construct_gf_linear
    datatype='seismic', component=var),
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/ffo/fault.py", line 161, in get_all_subfaults
    index=i, datatype=datatype, component=component))
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/ffo/fault.py", line 146, in get_subfault
    source_key = self.get_subfault_key(index, datatype, component)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/ffo/fault.py", line 88, in get_subfault_key
    self._check_datatype(datatype)
  File "/anaconda3/lib/python3.6/site-packages/beat-1.0rc1-py3.6-macosx-10.7-x86_64.egg/beat/ffo/fault.py", line 75, in _check_datatype
    'Datatype "%s" not included in FaultGeometry' % datatype)
TypeError: Datatype "seismic" not included in FaultGeometry

Can you give me some suggestions? Thank you very much.

**Comment by hvasbath** [comment]
Apparently, your fault was discretized only for seismic data. Please add a "--force" to your execution line and it should work.

**Comment by nanfang0422** [comment]
Thank you for your suggestions. It runs well now.
