### ISSUE TITLE
pyrocko.gf.meta.OutOfBounds: out of bounds

### ISSUE THREAD

**Issue by sandragharbi** [hvasbath/beat#49]
I am trying to run beat for MT calculations. I am using a downloaded Green's function (ak135_2000km_1Hz) that was converted to beat format and calculated the phases arrivals. But I am getting the error below when I try to compute the hypers:
beat sample --hypers
config       - INFO     All parameter-priors ok!
models       - INFO     ... Initialising Geometry Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

heart        - INFO     Consistent number of datasets and targets in any_S_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_S_0: 6 
models       - INFO     ... Building Hyper model ...

models       - INFO     Optimization for 1 hyperparameters in total!
seismic      - INFO     Retrieving seismic data-covariances with structure "identity" for any_S_0 ...
Traceback (most recent call last):
  File "/opt/anaconda2/bin/beat", line 4, in <module>
    __import__('pkg_resources').run_script('beat==1.0rc1', 'beat')
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/anaconda2/lib/python2.7/site-packages/beat-1.0rc1-py2.7-macosx-10.7-x86_64.egg/EGG-INFO/scripts/beat", line 1485, in <module>
    
  File "/opt/anaconda2/lib/python2.7/site-packages/beat-1.0rc1-py2.7-macosx-10.7-x86_64.egg/EGG-INFO/scripts/beat", line 664, in command_sample
    
  File "build/bdist.macosx-10.7-x86_64/egg/beat/models/problems.py", line 898, in load_model
  File "build/bdist.macosx-10.7-x86_64/egg/beat/models/problems.py", line 420, in built_hyper_model
  File "build/bdist.macosx-10.7-x86_64/egg/beat/models/seismic.py", line 123, in analyse_noise
  File "build/bdist.macosx-10.7-x86_64/egg/beat/covariance.py", line 272, in get_data_covariances
  File "build/bdist.macosx-10.7-x86_64/egg/beat/covariance.py", line 221, in do_variance_estimate
  File "build/bdist.macosx-10.7-x86_64/egg/beat/heart.py", line 1949, in get_phase_arrival_time
  File "/opt/anaconda2/lib/python2.7/site-packages/pyrocko/gf/store.py", line 1663, in t
    return timing.evaluate(self.get_phase, args)
  File "/opt/anaconda2/lib/python2.7/site-packages/pyrocko/gf/meta.py", line 528, in evaluate
    raise OutOfBounds(args)
pyrocko.gf.meta.OutOfBounds: out of bounds: (15,85047)
[config_geometry.txt](https://github.com/hvasbath/beat/files/4223895/config_geometry.txt)

**Comment by hvasbath** [comment]
Dear Sandra,

first of all welcome back ;) ! I strongly recommend to use python3, as we stopped supporting python2 one year ago and many things got fixed/changed by then. Then one strange thing in your config is that you only try to fit S waves- is that correct? Typically you would want to fit these on the T component for SH waves. To be able to run a successful inversion on SV waves you usually need to know your velocity model very well.

So please try running it on python3 first- then please report back if the error persists. If the error message changes please also post that!

Good luck!
