### ISSUE TITLE
KeyError: 'exponent'

### ISSUE THREAD

**Issue by icasallas** [hvasbath/beat#53]
Hi BEAT Team

I am trying to run the example about of section "Getting started with BEAT".  I run the line:

beat init LandersEQ 1992-06-28 --datatypes='seismic' --individual_gfs --n_sources=1 --source_type=MTSource --min_mag=7

However I got the following:

Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/beat/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0', 'console_scripts', 'beat')()
  File "/home/lab/anaconda3/envs/beat/lib/python3.6/site-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 1686, in main
    globals()['command_' + command](args)
  File "/home/lab/anaconda3/envs/beat/lib/python3.6/site-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 303, in command_init
    individual_gfs=options.individual_gfs)
  File "/home/lab/anaconda3/envs/beat/lib/python3.6/site-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/config.py", line 1437, in init_config
    c.problem_config.init_vars()
  File "/home/lab/anaconda3/envs/beat/lib/python3.6/site-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/config.py", line 725, in init_vars
    lower = default_bounds[variable][0]
KeyError: 'exponent'

As a result only the BEAT_log is generated, with one line that states (not much):

2020-05-11 21:25:32,868 - utility - INFO - Getting relevant events from the gCMT catalog for the dates:1992-06-27 00:00:00.000 - 1992-06-29 00:00:00.000 

Thanks in advance.
Best, 

Ivan C.

**Comment by hvasbath** [comment]
Dear Ivan,

thanks for reporting!
This should have been fixed in this commit:
https://github.com/hvasbath/beat/commit/6ac46792cc94acb592ab647dc1bcb46ddbd9e462

Can you please double check that you really have the most up to date version of BEAT installed!

Hannes

**Comment by icasallas** [comment]
Done. All right !

Thanks 

Ivan
