### ISSUE TITLE
station naming and store id

### ISSUE THREAD

**Issue by hvasbath** [hvasbath/beat#55]
Station names may start with numbers, but store IDs may NOT! leading to:

    beat build_gfs CalifBajaFullMT --datatypes='seismic'. And then, I have the following error message:

heart        - INFO     Using crust2 profile
heart        - INFO     Station 035Z
heart        - INFO     ---------------------
Traceback (most recent call last):
  File "/usr/local/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0', 'console_scripts', 'beat')()
  File "/usr/local/lib/python3.8/dist-packages/beat-1.0-py3.8-linux-x86_64.egg/beat/apps/beat.py", line 1686, in main
    globals()'command_' + command
  File "/usr/local/lib/python3.8/dist-packages/beat-1.0-py3.8-linux-x86_64.egg/beat/apps/beat.py", line 1032, in command_build_gfs
    heart.seis_construct_gf(
  File "/usr/local/lib/python3.8/dist-packages/beat-1.0-py3.8-linux-x86_64.egg/beat/heart.py", line 1663, in seis_construct_gf
    fomosto_config = get_fomosto_baseconfig(
  File "/usr/local/lib/python3.8/dist-packages/beat-1.0-py3.8-linux-x86_64.egg/beat/heart.py", line 1481, in get_fomosto_baseconfig
    return gf.ConfigTypeA(
  File "/usr/local/lib/python3.8/dist-packages/pyrocko/gf/meta.py", line 1606, in init
    self.validate(regularize=True, depth=1)
  File "/usr/local/lib/python3.8/dist-packages/pyrocko/guts.py", line 846, in validate
    self.T.instance.validate(self, regularize, depth)
  File "/usr/local/lib/python3.8/dist-packages/pyrocko/guts.py", line 545, in validate
    val = validator.validate_children(val, regularize, depth)
  File "/usr/local/lib/python3.8/dist-packages/pyrocko/guts.py", line 557, in validate_children
    newpropval = prop.validate(propval, regularize, depth-1)
  File "/usr/local/lib/python3.8/dist-packages/pyrocko/guts.py", line 542, in validate
    validator.validate_extra(val)
  File "/usr/local/lib/python3.8/dist-packages/pyrocko/guts.py", line 1306, in validate_extra
    raise ValidationError('%s: "%s" does not match pattern %s' % (
pyrocko.guts.ValidationError: id: "035Z_ak135_2.000Hz_0" does not match pattern '^[A-Za-z][A-Za-z0-9._]{0,64}$'

**Comment by hvasbath** [comment]
Needs fix in store specific naming scheme- however backwards compatibility needs to be ensured...
