### ISSUE TITLE
KeyError: 'opening_fraction

### ISSUE THREAD

**Issue by icasallas** [hvasbath/beat#81]
Dear all...Trying to init a project with geometry=RectangularSource and Geodetic Data

$ beat init DEQ 2019-12-15 --datatypes='geodetic' --n_sources=1 --source_type=RectangularSource --min_mag=6.6
utility      - INFO     Getting relevant events from the gCMT catalog for the dates:2019-12-14 00:00:00.000 - 2019-12-16 00:00:00.000 

Traceback (most recent call last):
  File "/usr/local/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0', 'console_scripts', 'beat')()
  File "/usr/local/lib/python3.6/dist-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 1688, in main
    globals()'command_' + command
  File "/usr/local/lib/python3.6/dist-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 303, in command_init
    individual_gfs=options.individual_gfs)
  File "/usr/local/lib/python3.6/dist-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/config.py", line 1437, in init_config
    c.problem_config.init_vars()
  File "/usr/local/lib/python3.6/dist-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/config.py", line 725, in init_vars
    lower = default_bounds[variable][0]
KeyError: 'opening_fraction'

**Comment by hvasbath** [comment]
You use the new pyrocko version v02042021, so you have to make sure to use the beat development branch v1.1_dev_rc
following this procedure: https://pyrocko.org/beat/docs/current/updating.html
